### ISSUE TITLE
Problem with Build

### ISSUE THREAD

**Issue by odinsride** [bizoo/OracleSQL#6]
Hi Bizoo,

I am brand new to ST2 and installed your OracleSQL package according to the instructions.  I am having errors with the Build command that calls sqlplus:

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 337, in run_
  File ".\oracle_exec.py", line 24, in run
  File ".\exec.py", line 130, in run
TypeError: sequence item 5: expected string or Unicode, NoneType found

I created the .sublime-build file with my DB instances, and chose Build from the menu.  Nothing happens, and the above error is shown in the console. Not sure where to even look to find the problem..any ideas?

Thanks!

**Comment by odinsride** [comment]
Nevermind, was trying to run the Build command on an unsaved file (just for testing the functionality). After saving it and giving it a filename, the Build command worked fine!
